let cName=document.getElementById("cityName");
let couName=document.getElementById("countryName");
let temp=document.getElementById("temperature");
let minTemp=document.getElementById("minTemperature");
let maxTemp=document.getElementById("maxTemperature");
// let cGiven;
// let couGiven;
cName.value=localStorage.getItem("cityD");
couName.value=localStorage.getItem("countryD");
// cName.value=cgiven;
let date=new Date();
let formatDate=date.toLocaleString(date);
document.getElementById("sideHeading").innerHTML=formatDate;